# https://taskfile.dev

version: '2'

env:
  AWS_DEFAULT_REGION: eu-central-1

tasks:
  build:
    desc: Build js files
      - npm run build

  build-go:
    desc: build go
    dir: lambda
    cmds:
      - env GOOS=linux go build -ldflags="-s -w" -o dist/main main/main.go
      - chmod +x dist/main
      - cd dist && zip main.zip main
    sources:
      - ./*.go
      - main/*.go
    generates:
      - dist/main
    silent: true

  update:
    desc: install latest cdk and other modules
    cmds:
      - ncu -u
      - npm install

  deploy:
    desc: deploy stack without asking
    deps: [build, build-go]
    cmds:
      - cmd: echo Profile $AWSUME_PROFILE
        silent: true
      - cdk deploy --require-approval never --profile $AWSUME_PROFILE

  diff:
    desc: diff stack 
    deps: [build, build-go]
    cmds:
      - cmd: echo Profile $AWSUME_PROFILE
        silent: true
      - cdk diff  --profile $AWSUME_PROFILE
      
  destroy:
    desc: destroy stack without asking
    cmds:
      - cmd: echo Profile $AWSUME_PROFILE
        silent: true
      - cdk destroy --force --profile $AWSUME_PROFILE

  edge-of-tomorrow:
    desc: deploy destroy repeat
    cmds:
      - task: update
      - task: deploy
      - task: destroy

