# https://taskfile.dev

version: '3'

env:
  AWS_DEFAULT_REGION: eu-central-1
  CDK_DEFAULT_REGION: eu-central-1
  CDK_DEFAULT_ACCOUNT: 
    sh: aws sts get-caller-identity --query Account --output text

  
tasks:
 
  update:
    desc: install latest cdk and other modules
    cmds:
      - go get -d github.com/aws/aws-cdk-go/awscdk/v2@{{.version}}
      - go get -d github.com/aws/constructs-go/constructs/v10@{{.constructs}}

  deploy:
    desc: deploy stack without asking
    cmds:
      - cmd: echo Profile $AWSUME_PROFILE
        silent: true
      - npx {{.npxoptions}} cdk@{{.version}}  deploy -c stage=dev --require-approval never --profile $AWSUME_PROFILE

  test:
    desc: Test infrastructure
    cmds:
      - go test -v

  destroy:
    desc: destroy stack without asking
    cmds:
      - cmd: echo Profile $AWSUME_PROFILE
        silent: true
      -  npx {{.npxoptions}} cdk@{{.version}}  destroy --force --profile $AWSUME_PROFILE

  edge-of-tomorrow:
    desc: deploy destroy repeat
    cmds:
      - task: update
      - task: deploy
      - task: test
      - task: destroy

  cit:
    desc: cdk infrastructure test
    cmds:
      - task: deploy
      - task: test
      - task: destroy

  generate-testdata:
    desc: Create json for testing
    cmds:
      - aws cloudformation get-template --stack-name IamUserStack >testdata/get-template.json
      - aws cloudformation describe-stack-resource --logical-resource-id student1000A84DF --stack-name IamUserStack >testdata/describe-stack-resource-user-1.json
      - aws iam get-user --user-name student_1 >testdata/user1.json
      - aws iam get-group --group-name IamUserStack-trainigsUserGroup4B8ABB6D-1AP9UWB57DW3C >testdata/group.json

  status:
    desc: State of clouformation
    cmds:
      - cdkstat    

