Conditions:
  CDKMetadataAvailable:
    Fn::Or:
    - Fn::Or:
      - Fn::Equals:
        - Ref: AWS::Region
        - ap-east-1
      - Fn::Equals:
        - Ref: AWS::Region
        - ap-northeast-1
      - Fn::Equals:
        - Ref: AWS::Region
        - ap-northeast-2
      - Fn::Equals:
        - Ref: AWS::Region
        - ap-south-1
      - Fn::Equals:
        - Ref: AWS::Region
        - ap-southeast-1
      - Fn::Equals:
        - Ref: AWS::Region
        - ap-southeast-2
      - Fn::Equals:
        - Ref: AWS::Region
        - ca-central-1
      - Fn::Equals:
        - Ref: AWS::Region
        - cn-north-1
      - Fn::Equals:
        - Ref: AWS::Region
        - cn-northwest-1
      - Fn::Equals:
        - Ref: AWS::Region
        - eu-central-1
    - Fn::Or:
      - Fn::Equals:
        - Ref: AWS::Region
        - eu-north-1
      - Fn::Equals:
        - Ref: AWS::Region
        - eu-west-1
      - Fn::Equals:
        - Ref: AWS::Region
        - eu-west-2
      - Fn::Equals:
        - Ref: AWS::Region
        - eu-west-3
      - Fn::Equals:
        - Ref: AWS::Region
        - me-south-1
      - Fn::Equals:
        - Ref: AWS::Region
        - sa-east-1
      - Fn::Equals:
        - Ref: AWS::Region
        - us-east-1
      - Fn::Equals:
        - Ref: AWS::Region
        - us-east-2
      - Fn::Equals:
        - Ref: AWS::Region
        - us-west-1
      - Fn::Equals:
        - Ref: AWS::Region
        - us-west-2
Outputs:
  ExportsOutputRefJenkinsServer4D09C9AB:
    Export:
      Name: AwsTestJenkinsStack:ExportsOutputRefJenkinsServer4D09C9AB
    Value:
      Ref: JenkinsServer
  JenkinsServerSG:
    Value:
      Fn::GetAtt:
      - WebServerSG4D0F372C
      - GroupId
  jenkins:
    Description: jenkins internal ip
    Value:
      Fn::GetAtt:
      - JenkinsServer
      - PrivateIp
Parameters:
  SsmParameterValueawsserviceamiamazonlinuxlatestamzn2amihvmx8664gp2C96584B6F00A464EAD1953AFF4B05118Parameter:
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
Resources:
  CDKMetadata:
    Condition: CDKMetadataAvailable
    Metadata:
      aws:cdk:path: AwsTestJenkinsStack/CDKMetadata/Default
    Properties:
      Modules: aws-cdk=1.83.0,@aws-cdk/assets=1.83.0,@aws-cdk/aws-cloudwatch=1.83.0,@aws-cdk/aws-ec2=1.83.0,@aws-cdk/aws-events=1.83.0,@aws-cdk/aws-iam=1.83.0,@aws-cdk/aws-kms=1.83.0,@aws-cdk/aws-logs=1.83.0,@aws-cdk/aws-s3=1.83.0,@aws-cdk/aws-s3-assets=1.83.0,@aws-cdk/aws-ssm=1.83.0,@aws-cdk/cloud-assembly-schema=1.83.0,@aws-cdk/core=1.83.0,@aws-cdk/cx-api=1.83.0,@aws-cdk/region-info=1.83.0,jsii-runtime=node.js/v12.14.1
    Type: AWS::CDK::Metadata
  JenkinsServer:
    Metadata:
      aws:cdk:path: AwsTestJenkinsStack/JenkinsServer
    Properties:
      ImageId:
        Ref: SsmParameterValueawsserviceamiamazonlinuxlatestamzn2amihvmx8664gp2C96584B6F00A464EAD1953AFF4B05118Parameter
      InstanceType: c5.large
      SecurityGroupIds:
      - Fn::GetAtt:
        - WebServerSG4D0F372C
        - GroupId
      SubnetId:
        Ref: TheVPCPublicSubnet1Subnet770D4FF2
      Tags:
      - Key: Name
        Value: JenkinsServer
      UserData: IyEvYmluL2Jhc2gKeXVtIHVwZGF0ZSDigJN5CmFtYXpvbi1saW51eC1leHRyYXMgZW5hYmxlIGNvcnJldHRvOAp5dW0gaW5zdGFsbCBqYXZhLTEuOC4wLWFtYXpvbi1jb3JyZXR0by1kZXZlbCAteQp3Z2V0IC1PIC9ldGMveXVtLnJlcG9zLmQvamVua2lucy5yZXBvIGh0dHA6Ly9wa2cuamVua2lucy1jaS5vcmcvcmVkaGF0L2plbmtpbnMucmVwbyAtLXRpbWVvdXQ9MzAKcnBtIC0taW1wb3J0IGh0dHBzOi8vcGtnLmplbmtpbnMuaW8vcmVkaGF0L2plbmtpbnMuaW8ua2V5Cnl1bSBpbnN0YWxsIGplbmtpbnMgLXkKc2VydmljZSBqZW5raW5zIHN0YXJ0Cnl1bSAteSBpbnN0YWxsIGdpdCBkb2NrZXIK
    Type: AWS::EC2::Instance
  JenkinsServerProfile:
    Metadata:
      aws:cdk:path: AwsTestJenkinsStack/JenkinsServerProfile
    Properties:
      Roles:
      - Ref: jenkinsinstancerole1416A36A
    Type: AWS::IAM::InstanceProfile
  TheVPC92636AB0:
    Metadata:
      aws:cdk:path: AwsTestJenkinsStack/TheVPC/Resource
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: AwsTestJenkinsStack/TheVPC
    Type: AWS::EC2::VPC
  TheVPCIGWFA25CC08:
    Metadata:
      aws:cdk:path: AwsTestJenkinsStack/TheVPC/IGW
    Properties:
      Tags:
      - Key: Name
        Value: AwsTestJenkinsStack/TheVPC
    Type: AWS::EC2::InternetGateway
  TheVPCPrivateSubnet1DefaultRouteD1B9E467:
    Metadata:
      aws:cdk:path: AwsTestJenkinsStack/TheVPC/PrivateSubnet1/DefaultRoute
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: TheVPCPublicSubnet1NATGatewayC61D892B
      RouteTableId:
        Ref: TheVPCPrivateSubnet1RouteTableF6513BC2
    Type: AWS::EC2::Route
  TheVPCPrivateSubnet1RouteTableAssociation46F1FFFC:
    Metadata:
      aws:cdk:path: AwsTestJenkinsStack/TheVPC/PrivateSubnet1/RouteTableAssociation
    Properties:
      RouteTableId:
        Ref: TheVPCPrivateSubnet1RouteTableF6513BC2
      SubnetId:
        Ref: TheVPCPrivateSubnet1Subnet571D3690
    Type: AWS::EC2::SubnetRouteTableAssociation
  TheVPCPrivateSubnet1RouteTableF6513BC2:
    Metadata:
      aws:cdk:path: AwsTestJenkinsStack/TheVPC/PrivateSubnet1/RouteTable
    Properties:
      Tags:
      - Key: Name
        Value: AwsTestJenkinsStack/TheVPC/PrivateSubnet1
      VpcId:
        Ref: TheVPC92636AB0
    Type: AWS::EC2::RouteTable
  TheVPCPrivateSubnet1Subnet571D3690:
    Metadata:
      aws:cdk:path: AwsTestJenkinsStack/TheVPC/PrivateSubnet1/Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
        - 0
        - Fn::GetAZs: ''
      CidrBlock: 10.0.128.0/18
      MapPublicIpOnLaunch: false
      Tags:
      - Key: aws-cdk:subnet-name
        Value: Private
      - Key: aws-cdk:subnet-type
        Value: Private
      - Key: Name
        Value: AwsTestJenkinsStack/TheVPC/PrivateSubnet1
      VpcId:
        Ref: TheVPC92636AB0
    Type: AWS::EC2::Subnet
  TheVPCPrivateSubnet2DefaultRoute52A1F245:
    Metadata:
      aws:cdk:path: AwsTestJenkinsStack/TheVPC/PrivateSubnet2/DefaultRoute
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: TheVPCPublicSubnet2NATGatewayB437CFAF
      RouteTableId:
        Ref: TheVPCPrivateSubnet2RouteTable9AC81FAC
    Type: AWS::EC2::Route
  TheVPCPrivateSubnet2RouteTable9AC81FAC:
    Metadata:
      aws:cdk:path: AwsTestJenkinsStack/TheVPC/PrivateSubnet2/RouteTable
    Properties:
      Tags:
      - Key: Name
        Value: AwsTestJenkinsStack/TheVPC/PrivateSubnet2
      VpcId:
        Ref: TheVPC92636AB0
    Type: AWS::EC2::RouteTable
  TheVPCPrivateSubnet2RouteTableAssociation336D47D1:
    Metadata:
      aws:cdk:path: AwsTestJenkinsStack/TheVPC/PrivateSubnet2/RouteTableAssociation
    Properties:
      RouteTableId:
        Ref: TheVPCPrivateSubnet2RouteTable9AC81FAC
      SubnetId:
        Ref: TheVPCPrivateSubnet2SubnetCC3D7013
    Type: AWS::EC2::SubnetRouteTableAssociation
  TheVPCPrivateSubnet2SubnetCC3D7013:
    Metadata:
      aws:cdk:path: AwsTestJenkinsStack/TheVPC/PrivateSubnet2/Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
        - 1
        - Fn::GetAZs: ''
      CidrBlock: 10.0.192.0/18
      MapPublicIpOnLaunch: false
      Tags:
      - Key: aws-cdk:subnet-name
        Value: Private
      - Key: aws-cdk:subnet-type
        Value: Private
      - Key: Name
        Value: AwsTestJenkinsStack/TheVPC/PrivateSubnet2
      VpcId:
        Ref: TheVPC92636AB0
    Type: AWS::EC2::Subnet
  TheVPCPublicSubnet1DefaultRoute6D26543F:
    DependsOn:
    - TheVPCVPCGWC9B93E30
    Metadata:
      aws:cdk:path: AwsTestJenkinsStack/TheVPC/PublicSubnet1/DefaultRoute
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: TheVPCIGWFA25CC08
      RouteTableId:
        Ref: TheVPCPublicSubnet1RouteTable17DA183D
    Type: AWS::EC2::Route
  TheVPCPublicSubnet1EIP4412F690:
    Metadata:
      aws:cdk:path: AwsTestJenkinsStack/TheVPC/PublicSubnet1/EIP
    Properties:
      Domain: vpc
      Tags:
      - Key: Name
        Value: AwsTestJenkinsStack/TheVPC/PublicSubnet1
    Type: AWS::EC2::EIP
  TheVPCPublicSubnet1NATGatewayC61D892B:
    Metadata:
      aws:cdk:path: AwsTestJenkinsStack/TheVPC/PublicSubnet1/NATGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
        - TheVPCPublicSubnet1EIP4412F690
        - AllocationId
      SubnetId:
        Ref: TheVPCPublicSubnet1Subnet770D4FF2
      Tags:
      - Key: Name
        Value: AwsTestJenkinsStack/TheVPC/PublicSubnet1
    Type: AWS::EC2::NatGateway
  TheVPCPublicSubnet1RouteTable17DA183D:
    Metadata:
      aws:cdk:path: AwsTestJenkinsStack/TheVPC/PublicSubnet1/RouteTable
    Properties:
      Tags:
      - Key: Name
        Value: AwsTestJenkinsStack/TheVPC/PublicSubnet1
      VpcId:
        Ref: TheVPC92636AB0
    Type: AWS::EC2::RouteTable
  TheVPCPublicSubnet1RouteTableAssociationE5186D77:
    Metadata:
      aws:cdk:path: AwsTestJenkinsStack/TheVPC/PublicSubnet1/RouteTableAssociation
    Properties:
      RouteTableId:
        Ref: TheVPCPublicSubnet1RouteTable17DA183D
      SubnetId:
        Ref: TheVPCPublicSubnet1Subnet770D4FF2
    Type: AWS::EC2::SubnetRouteTableAssociation
  TheVPCPublicSubnet1Subnet770D4FF2:
    Metadata:
      aws:cdk:path: AwsTestJenkinsStack/TheVPC/PublicSubnet1/Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
        - 0
        - Fn::GetAZs: ''
      CidrBlock: 10.0.0.0/18
      MapPublicIpOnLaunch: true
      Tags:
      - Key: aws-cdk:subnet-name
        Value: Public
      - Key: aws-cdk:subnet-type
        Value: Public
      - Key: Name
        Value: AwsTestJenkinsStack/TheVPC/PublicSubnet1
      VpcId:
        Ref: TheVPC92636AB0
    Type: AWS::EC2::Subnet
  TheVPCPublicSubnet2DefaultRouteFEB062B2:
    DependsOn:
    - TheVPCVPCGWC9B93E30
    Metadata:
      aws:cdk:path: AwsTestJenkinsStack/TheVPC/PublicSubnet2/DefaultRoute
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: TheVPCIGWFA25CC08
      RouteTableId:
        Ref: TheVPCPublicSubnet2RouteTable3609F42C
    Type: AWS::EC2::Route
  TheVPCPublicSubnet2EIP5AAFF9FA:
    Metadata:
      aws:cdk:path: AwsTestJenkinsStack/TheVPC/PublicSubnet2/EIP
    Properties:
      Domain: vpc
      Tags:
      - Key: Name
        Value: AwsTestJenkinsStack/TheVPC/PublicSubnet2
    Type: AWS::EC2::EIP
  TheVPCPublicSubnet2NATGatewayB437CFAF:
    Metadata:
      aws:cdk:path: AwsTestJenkinsStack/TheVPC/PublicSubnet2/NATGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
        - TheVPCPublicSubnet2EIP5AAFF9FA
        - AllocationId
      SubnetId:
        Ref: TheVPCPublicSubnet2Subnet73F96DA9
      Tags:
      - Key: Name
        Value: AwsTestJenkinsStack/TheVPC/PublicSubnet2
    Type: AWS::EC2::NatGateway
  TheVPCPublicSubnet2RouteTable3609F42C:
    Metadata:
      aws:cdk:path: AwsTestJenkinsStack/TheVPC/PublicSubnet2/RouteTable
    Properties:
      Tags:
      - Key: Name
        Value: AwsTestJenkinsStack/TheVPC/PublicSubnet2
      VpcId:
        Ref: TheVPC92636AB0
    Type: AWS::EC2::RouteTable
  TheVPCPublicSubnet2RouteTableAssociationB4B0A733:
    Metadata:
      aws:cdk:path: AwsTestJenkinsStack/TheVPC/PublicSubnet2/RouteTableAssociation
    Properties:
      RouteTableId:
        Ref: TheVPCPublicSubnet2RouteTable3609F42C
      SubnetId:
        Ref: TheVPCPublicSubnet2Subnet73F96DA9
    Type: AWS::EC2::SubnetRouteTableAssociation
  TheVPCPublicSubnet2Subnet73F96DA9:
    Metadata:
      aws:cdk:path: AwsTestJenkinsStack/TheVPC/PublicSubnet2/Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
        - 1
        - Fn::GetAZs: ''
      CidrBlock: 10.0.64.0/18
      MapPublicIpOnLaunch: true
      Tags:
      - Key: aws-cdk:subnet-name
        Value: Public
      - Key: aws-cdk:subnet-type
        Value: Public
      - Key: Name
        Value: AwsTestJenkinsStack/TheVPC/PublicSubnet2
      VpcId:
        Ref: TheVPC92636AB0
    Type: AWS::EC2::Subnet
  TheVPCVPCGWC9B93E30:
    Metadata:
      aws:cdk:path: AwsTestJenkinsStack/TheVPC/VPCGW
    Properties:
      InternetGatewayId:
        Ref: TheVPCIGWFA25CC08
      VpcId:
        Ref: TheVPC92636AB0
    Type: AWS::EC2::VPCGatewayAttachment
  WebServerSG4D0F372C:
    Metadata:
      aws:cdk:path: AwsTestJenkinsStack/WebServerSG/Resource
    Properties:
      GroupDescription: WebServerSG
      GroupName: jenkinsServer
      SecurityGroupEgress:
      - CidrIp: 0.0.0.0/0
        Description: Allow all outbound traffic by default
        IpProtocol: '-1'
      SecurityGroupIngress:
      - CidrIp: 10.0.0.0/16
        Description: Ssh incoming
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
      - CidrIp: 10.0.0.0/16
        Description: http incoming
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
      - CidrIp: 10.0.0.0/16
        Description: jenkins incoming
        FromPort: 8080
        IpProtocol: tcp
        ToPort: 8080
      - CidrIp:
          Fn::GetAtt:
          - TheVPC92636AB0
          - CidrBlock
        Description: jenkins incoming
        FromPort: 8080
        IpProtocol: tcp
        ToPort: 8080
      VpcId:
        Ref: TheVPC92636AB0
    Type: AWS::EC2::SecurityGroup
  jenkinsinstancerole1416A36A:
    Metadata:
      aws:cdk:path: AwsTestJenkinsStack/jenkinsinstancerole/Resource
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
              Fn::Join:
              - ''
              - - ec2.
                - Ref: AWS::URLSuffix
        Version: '2012-10-17'
      ManagedPolicyArns:
      - Fn::Join:
        - ''
        - - 'arn:'
          - Ref: AWS::Partition
          - :iam::aws:policy/service-role/AmazonEC2RoleforSSM
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:ListQueues
            - sqs:DeleteMessageBatch
            - sqs:GetQueueAttributes
            - sqs:ListQueues
            Effect: Allow
            Resource: '*'
            Sid: '0'
          Version: '2012-10-17'
        PolicyName: CodeBuildJenkinsPlugin
    Type: AWS::IAM::Role
