# https://taskfile.dev

version: '2'

vars:
  GREETING: Hello, World!
  REPO: 'myhugorepositoryname'
  CDK_DIR: '/Users/silberkopf/projects/cdk/cdk-templates/codepipeline'
 
tasks:
  default:
    cmds:
      - task --list
    silent: true

  git_init:
    dir: quickstart
    cmds:
      - git init
      - git submodule add https://github.com/xaprb/story.git themes/story
      - git remote add origin https://git-codecommit.eu-central-1.amazonaws.com/v1/repos/{{.REPO}}

  hugo_init:
    dir: quickstart
    cmds:
      - cp {{.CDK_DIR}}/assets/buildspec.yml .
      - echo 'theme = "story"' >> config.toml
      - hugo new posts/my-first-post.md
      - echo public >>.gitignore

  hugo_push_first:
    dir: quickstart
    cmds:
      - git add .
      - git commit -m "minor changes"
      - git push --set-upstream origin master

  1_Deploy_Pipeline:
    desc: CDK Deploy Pipeline
    dir: "{{.CDK_DIR}}"
    cmds:
      - cdk deploy

  2_Create_Hugo:
    desc: Create and push hugo quickstart website
    cmds:
      - hugo new site quickstart
      - task: git_init
      - task: hugo_init
      - task: hugo_push_first

  3_Destroy_Pipeline:
    desc: Delete CDK Pipeline (S3 Bucket remains)
    dir: "{{.CDK_DIR}}"
    cmds:
     - cdk destroy

