# https://taskfile.dev

version: '3'

env:
  AWS_DEFAULT_REGION: eu-central-1
  CDK_DEFAULT_REGION: eu-central-1
  CDK_DEFAULT_ACCOUNT:
    sh: aws sts get-caller-identity --query Account --output text

# Uncomment if calling task from this directory,
# not from uper directory
vars:
  version: v2.47.0
  constructs: v10.1.139

tasks:

  update:
    desc: install latest cdk and other modules
    cmds:
      - go get -d github.com/aws/aws-cdk-go/awscdk/v2@{{.version}}
      - go get -d github.com/aws/constructs-go/constructs/v10@{{.constructs}}

  bootstrap:
    desc: bootstrap account
    cmds:
      - cdk bootstrap

  deploy:
    desc: deploy stack without asking
    cmds:
      - cmd: echo Profile $AWSUME_PROFILE
        silent: true
      - npx {{.npxoptions}} cdk@{{.version}}  deploy -c stage=dev --require-approval never --profile $AWSUME_PROFILE


  destroy:
    desc: destroy stack without asking
    cmds:
      - cmd: echo Profile $AWSUME_PROFILE
        silent: true
      -  npx {{.npxoptions}} cdk@{{.version}}  destroy --force --profile $AWSUME_PROFILE

  edge-of-tomorrow:
    desc: deploy destroy repeat
    cmds:
      - task: update
      - task: deploy
      - task: test
      - task: destroy

  fix:
    desc: x/sys/unix error
    cmds:
      - go get golang.org/x/sys/unix


  cit:
    desc: cdk infrastructure test
    cmds:
      - task: deploy
      - task: test
      - task: destroy

  test:
    desc: Unit Test Cloudformation generation
    cmds:
      - go test -short -v
    silent: true

  itest:
    desc: Test infrastructure
    cmds:
      - go test  -v
