# https://taskfile.dev

version: '3'

env:
  AWS_DEFAULT_REGION: eu-central-1
  CDK_DEFAULT_REGION: eu-central-1
  CDK_DEFAULT_ACCOUNT: 
    sh: aws sts get-caller-identity --query Account --output text

# Uncomment if calling task from this directory,
# not from uper directory
vars:
  version: v2.0.0-rc.7
  constructs: v10.0.5

includes:
  lambda: 
    taskfile: ./app/Taskfile.yml
    dir: ./lambda

tasks: 
  update:
    dir: infra
    desc: install latest cdk and other modules
    cmds:
      - go get -d github.com/aws/aws-cdk-go/awscdk/v2@{{.version}}
      - go get -d github.com/aws/constructs-go/constructs/v10@{{.constructs}}

  deploy:
    dir: infra
    desc: deploy stack without asking
    cmds:
      - cmd: echo Profile $AWSUME_PROFILE
        silent: true
      - npx {{.npxoptions}} cdk@{{.version}}  deploy -c stage=dev --require-approval never --profile $AWSUME_PROFILE


  destroy:
    dir: infra
    desc: destroy stack without asking
    cmds:
      - cmd: echo Profile $AWSUME_PROFILE
        silent: true
      -  npx {{.npxoptions}} cdk@{{.version}}  destroy --force --profile $AWSUME_PROFILE

  edge-of-tomorrow:
    dir: infra
    desc: deploy destroy repeat
    cmds:
      - task: update
      - task: deploy
      - task: test
      - task: destroy

  cit:
    dir: infra
    desc: cdk infrastructure test whole cycle
    cmds:
      - task: deploy
      - task: test
      - task: destroy

  test-unit:
    dir: infra
    desc: Unit Test CloudFormation generation
    cmds:
      - go test -short -v
    silent: true

  test-infra:
    dir: infra
    desc: Test infrastructure
    cmds:
      - go test  -v

  test-app:
    desc: Test lambda go app
    dir: infra
    cmds:
      - go test  -v
      

  app-build:
    desc: Build lambda go app 
    cmds:
      - task: lambda:build



